"""E3: scratch ES256 tokens for P3-PRIV-R, signed with OpenSSL alone (no cryptography library).

It proves the supported Supabase path for a custom-role JWT. A project trusts its imported,
rotated-in signing key, a P-256 key with a kid. A token it signs carries the role claim and a
short expiry. The key is generated by OpenSSL on the CI runner for one run. It lives in
RUNNER_TEMP and is never printed; only its public half leaves the runner's memory, as the JWKS that
the second PostgREST trusts.
"""

from __future__ import annotations

import base64
import json
import subprocess
import sys
import time

KID = "ucpe-scratch-es256"
_COORDINATE = 32


def b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def public_point(key_file: str) -> tuple[bytes, bytes]:
    """The key's public point (x, y), from OpenSSL's DER SubjectPublicKeyInfo."""

    der = subprocess.run(
        ["openssl", "ec", "-in", key_file, "-pubout", "-outform", "DER"],
        capture_output=True, check=True,
    ).stdout
    point = der[-(1 + 2 * _COORDINATE):]
    if point[0] != 0x04:
        raise ValueError("not an uncompressed P-256 point")
    return point[1:1 + _COORDINATE], point[1 + _COORDINATE:]


def jwks(key_file: str, kid: str = KID) -> dict:
    x, y = public_point(key_file)
    key = {"kty": "EC", "crv": "P-256", "x": b64url(x), "y": b64url(y), "kid": kid,
           "alg": "ES256", "use": "sig"}
    return {"keys": [key]}


def der_to_jose(signature: bytes) -> bytes:
    """An OpenSSL ECDSA signature (a DER SEQUENCE of two INTEGERs) as JOSE's r || s."""

    if len(signature) < 8 or signature[0] != 0x30 or signature[1] & 0x80:
        raise ValueError("not a short-form DER ECDSA signature")
    index, parts = 2, []
    for _ in range(2):
        if signature[index] != 0x02:
            raise ValueError("not a DER INTEGER")
        length = signature[index + 1]
        value = signature[index + 2:index + 2 + length].lstrip(b"\0")
        if len(value) > _COORDINATE:
            raise ValueError("an ECDSA integer longer than P-256's")
        parts.append(value.rjust(_COORDINATE, b"\0"))
        index += 2 + length
    if index != len(signature):
        raise ValueError("trailing bytes after the DER signature")
    return b"".join(parts)


def mint(
    key_file: str,
    role: str,
    *,
    kid: str = KID,
    now: int | None = None,
    lifetime: int = 600,
    subject: str = "ucpe-rehearsal",
) -> str:
    """A compact ES256 JWT with the kid header and the role, sub, iat and exp claims."""

    issued = int(time.time()) if now is None else now
    header = {"alg": "ES256", "typ": "JWT", "kid": kid}
    claims = {"role": role, "sub": subject, "iat": issued, "exp": issued + lifetime}
    signing_input = ".".join(
        b64url(json.dumps(part, separators=(",", ":"), sort_keys=True).encode("utf-8"))
        for part in (header, claims)
    )
    der = subprocess.run(
        ["openssl", "dgst", "-sha256", "-sign", key_file],
        input=signing_input.encode("ascii"), capture_output=True, check=True,
    ).stdout
    return f"{signing_input}.{b64url(der_to_jose(der))}"


if __name__ == "__main__":
    # The workflow builds the second PostgREST's trusted key set from the scratch key file.
    print(json.dumps(jwks(sys.argv[1]), separators=(",", ":")))
